### ISSUE TITLE
Not an issue just need help

### ISSUE THREAD

**Issue by jaiminj1** [atika/Ubersicht-Youtube#1]
I don't know how to use this

Change the absolute path of the command in the widget script.
command: "/usr/local/bin/node /full/path/to/the/Command/Youtube/youtube.js"

**Comment by atika** [comment]
Hi, Just see your message.

Just before, **the widget no longer works and I doesn't have time to work on it** for the moment..
Youtube changed the API 1/2 month ago and stopped the simple way I used to retrieve information. 

Instead of put the full command here, I made a separate script/program in NodeJS language to get the data from Youtube for the widget. I created a folder named "widgets" and other folder named "commands".
For exemple, If the NodeJs script (command) is located in folder : `~/Documents/Ubersicht/Commands/Youtube/youtube.js` you can put this :

```
command: "/usr/local/bin/node /Users/YouUsername/Documents/Ubersicht/Commands/Youtube/youtube.js"
```

**Comment by MetalsnakeMC** [comment]
Well I don't know what that means so I can't use it but thanks for your info
